### ISSUE TITLE
Does VAE model supports Tacotron 2 ?

### ISSUE THREAD

**Issue by rishikksh20** [yanggeng1995/vae_tacotron#1]
Nice implementation of VAE tacotron paper though I havn't read paper yet ,but start model training with LJSpeech. As I see this code is extending the Tacotron 1 implementation so I am bit curious that weather same VAE implementation possible with Tacotron 2 ?

**Note :** On paper, author used Tacotron 2.

**Comment by yanggeng1995** [comment]
yes, the experiments in this paper were carried out based on tacotron2, and I also implemented vae on tacotron2. Due to some research relations, it cannot be made public for the time being. You can refer to tacotron1 for migration

**Comment by rishikksh20** [comment]
Ok thanks, just a thing, the hyperparameter of VAE remain same for Tacotron 2 as of this repo or some thing needed to tweak for better performance? 
And roughly how much step/iteration it will take to converge with current implementation (for LJSpeech 22.5k) ?

Thanks in Advance :+1:

**Comment by yanggeng1995** [comment]
My experiment with tacotron2 just got going, and it hasn't worked out yet, so you can listen to the example the author gave(http://home.ustc.edu.cn/~zyj008/ICASSP2019/)

**Comment by rishikksh20** [comment]
`util` and `datasets` folders are not uploaded, I have copied from keithito's implementation.
But still get :
```
    from util.util import shape_list, vae_weight 
ImportError: No module named 'util.util'
```
may be some file not uploaded.

**Comment by yanggeng1995** [comment]
Sorry, I forgot to upload these two folders. I just uploaded them。
